/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author xiels
 */
public class FormPopupBuku extends javax.swing.JFrame {
    Connection conn = koneksi.getKoneksi();
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPopupBuku.class.getName());

    /**
     * Creates new form FormPopupBuku
     */
    public FormPopupBuku() {
        initComponents();
        tampilData();
        setLocationRelativeTo(null);
    }
    
private void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Judul");
    model.addColumn("Pengarang");
    model.addColumn("Penerbit");
    model.addColumn("Tahun");
    model.addColumn("Kategori");
    model.addColumn("Status");

    String cari = txtcari.getText();

    try {

        Connection conn = koneksi.getKoneksi();
        Statement st = conn.createStatement();

        String sql = "SELECT * FROM buku WHERE " +
                     "id_buku LIKE '%" + cari + "%' OR " +
                     "judul_buku LIKE '%" + cari + "%' OR " +
                     "pengarang LIKE '%" + cari + "%' OR " +
                     "kategori LIKE '%" + cari + "%'";

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_buku"),
                rs.getString("judul_buku"),
                rs.getString("pengarang"),
                rs.getString("penerbit"),
                rs.getString("tahun_terbit"),
                rs.getString("kategori"),
                rs.getString("status_buku")
            });
        }

        tblbuku.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblbuku = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btncaribuku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 78, 59));
        jLabel2.setText("Pop Up Buku");

        tblbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Anggota", "Nama", "No.Hp", "Jenis Kelamin", "Alamat"
            }
        ));
        tblbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbukuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblbuku);

        btncaribuku.setBackground(new java.awt.Color(6, 78, 59));
        btncaribuku.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btncaribuku.setForeground(new java.awt.Color(255, 255, 255));
        btncaribuku.setText("Cari");
        btncaribuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncaribukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncaribukuMouseExited(evt);
            }
        });
        btncaribuku.addActionListener(this::btncaribukuActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncaribukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaribukuActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btncaribukuActionPerformed

    private void tblbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbukuMouseClicked
        // TODO add your handling code here:int baris = tblbuku.getSelectedRow();
        int baris = tblbuku.getSelectedRow();

        if (baris == -1) {
            return;
        }

        String status = tblbuku.getValueAt(baris, 6).toString();

        if (status.equals("Dipinjam")) {
            JOptionPane.showMessageDialog(null, "Buku tidak tersedia karena sedang dipinjam");
            return;
        }

        FormPeminjaman.txtidbuku.setText(tblbuku.getValueAt(baris, 0).toString());
        FormPeminjaman.txtjudul.setText(tblbuku.getValueAt(baris, 1).toString());
        FormPeminjaman.txtpengarang.setText(tblbuku.getValueAt(baris, 2).toString());
        FormPeminjaman.txtpenerbit.setText(tblbuku.getValueAt(baris, 3).toString());
        FormPeminjaman.txttahun.setText(tblbuku.getValueAt(baris, 4).toString());
        FormPeminjaman.txtkategori.setText(tblbuku.getValueAt(baris, 5).toString());

        dispose();
    }//GEN-LAST:event_tblbukuMouseClicked

    private void btncaribukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaribukuMouseExited
        // TODO add your handling code here:
        btncaribuku.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btncaribukuMouseExited

    private void btncaribukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaribukuMouseEntered
        // TODO add your handling code here:
        btncaribuku.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btncaribukuMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPopupBuku().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncaribuku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblbuku;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
