/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author xiels
 */
public class FormPopupPeminjaman extends javax.swing.JFrame {
    Connection conn = koneksi.getKoneksi();
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPopupPeminjaman.class.getName());

    /**
     * Creates new form FormPopupPeminjaman
     */
    public FormPopupPeminjaman() {
        initComponents();
        tampilData();
        setLocationRelativeTo(null);
    }
    
    private void tampilData() {

    model = new DefaultTableModel();

    model.addColumn("ID Peminjaman");
    model.addColumn("Tanggal Pinjam");
    model.addColumn("ID Anggota");
    model.addColumn("Nama Anggota");
    model.addColumn("ID Buku");
    model.addColumn("Judul Buku");
    model.addColumn("ID Petugas");
    model.addColumn("Tenggat Kembali");

    String cari = txtcari.getText();

    try {

        Statement st = conn.createStatement();

        String sql = "SELECT "
           + "peminjaman.id_peminjaman, "
           + "peminjaman.tanggal_pinjam, "
           + "peminjaman.id_anggota, "
           + "anggota.nama_anggota, "
           + "GROUP_CONCAT(isi_peminjaman.id_buku ORDER BY isi_peminjaman.id_buku SEPARATOR ', ') AS id_buku, "
           + "GROUP_CONCAT(buku.judul_buku ORDER BY buku.id_buku SEPARATOR ', ') AS judul_buku, "
           + "peminjaman.id_petugas, "
           + "peminjaman.tenggat_kembali "
           + "FROM peminjaman "
           + "JOIN anggota ON peminjaman.id_anggota = anggota.id_anggota "
           + "JOIN isi_peminjaman ON peminjaman.id_peminjaman = isi_peminjaman.id_peminjaman "
           + "JOIN buku ON isi_peminjaman.id_buku = buku.id_buku "
           + "WHERE peminjaman.id_peminjaman NOT IN "
           + "(SELECT id_peminjaman FROM pengembalian) "
           + "GROUP BY "
           + "peminjaman.id_peminjaman, "
           + "peminjaman.tanggal_pinjam, "
           + "peminjaman.id_anggota, "
           + "anggota.nama_anggota, "
           + "peminjaman.id_petugas, "
           + "peminjaman.tenggat_kembali "
           + "HAVING peminjaman.id_peminjaman LIKE '%" + cari + "%' OR "
           + "peminjaman.tanggal_pinjam LIKE '%" + cari + "%' OR "
           + "peminjaman.id_anggota LIKE '%" + cari + "%' OR "
           + "anggota.nama_anggota LIKE '%" + cari + "%' OR "
           + "id_buku LIKE '%" + cari + "%' OR "
           + "judul_buku LIKE '%" + cari + "%' "
           + "ORDER BY peminjaman.id_peminjaman ASC";

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_peminjaman"),
                rs.getString("tanggal_pinjam"),
                rs.getString("id_anggota"),
                rs.getString("nama_anggota"),
                rs.getString("id_buku"),
                rs.getString("judul_buku"),
                rs.getString("id_petugas"),
                rs.getString("tenggat_kembali")
            });
        }

        tblpeminjaman.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcari = new javax.swing.JTextField();
        btncaripeminjaman = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpeminjaman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));

        btncaripeminjaman.setBackground(new java.awt.Color(6, 78, 59));
        btncaripeminjaman.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btncaripeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        btncaripeminjaman.setText("Cari");
        btncaripeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncaripeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncaripeminjamanMouseExited(evt);
            }
        });
        btncaripeminjaman.addActionListener(this::btncaripeminjamanActionPerformed);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 78, 59));
        jLabel2.setText("Pop Up Peminjaman");

        tblpeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Peminjaman", "Tanggal Peminjaman", "ID Anggota", "ID Buku", "ID Petugas", "Tenggat Kembali"
            }
        ));
        tblpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpeminjaman);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncaripeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncaripeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncaripeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripeminjamanActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btncaripeminjamanActionPerformed

    private void tblpeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpeminjamanMouseClicked
        // TODO add your handling code here:
        int baris = tblpeminjaman.getSelectedRow();

        String idPinjam = tblpeminjaman.getValueAt(baris, 0).toString();
        String tanggalPinjam = tblpeminjaman.getValueAt(baris, 1).toString();
        String idAnggota = tblpeminjaman.getValueAt(baris, 2).toString();
        String namaAnggota = tblpeminjaman.getValueAt(baris, 3).toString();
        String idBuku = tblpeminjaman.getValueAt(baris, 4).toString();
        String judulBuku = tblpeminjaman.getValueAt(baris, 5).toString();
        String tenggat = tblpeminjaman.getValueAt(baris, 7).toString();

        FormPengembalian.txtidpinjam.setText(idPinjam);
        FormPengembalian.txtidanggota.setText(idAnggota);
        FormPengembalian.txtnamaanggota.setText(namaAnggota);
        FormPengembalian.txtidbuku.setText(idBuku);
        FormPengembalian.txtjudul.setText(judulBuku);
        FormPengembalian.txttanggalpinjam.setText(tanggalPinjam);
        FormPengembalian.txttenggat.setText(tenggat);

        dispose();
    }//GEN-LAST:event_tblpeminjamanMouseClicked

    private void btncaripeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaripeminjamanMouseEntered
        // TODO add your handling code here:
        btncaripeminjaman.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btncaripeminjamanMouseEntered

    private void btncaripeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaripeminjamanMouseExited
        // TODO add your handling code here:
        btncaripeminjaman.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btncaripeminjamanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPopupPeminjaman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncaripeminjaman;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpeminjaman;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
