/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import koneksi.Session;
import javax.swing.JSpinner;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author xiels
 */
public class FormPeminjaman extends javax.swing.JFrame {
    Connection conn = koneksi.getKoneksi();
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPeminjaman.class.getName());

    /**
     * Creates new form FormPinjam
     */
    public FormPeminjaman() {
    initComponents();
    txtidpinjam.setEditable(false);
    labelid.setText(Session.getIdPetugas());
    labelnama.setText(Session.getNamaPetugas());
    sptanggal.setModel(new javax.swing.SpinnerDateModel());
    sptenggat.setModel(new javax.swing.SpinnerDateModel());
    JSpinner.DateEditor de1 =new JSpinner.DateEditor(sptanggal,"yyyy-MM-dd");sptanggal.setEditor(de1);
    JSpinner.DateEditor de2 =new JSpinner.DateEditor(sptenggat,"yyyy-MM-dd");sptenggat.setEditor(de2);
    nonAktif();
    autoID();
    tampilData();
    resetForm();
}
    
private void tampilData() {
    String[] judul = {
        "No",
        "ID Buku",
        "Judul Buku",
        "Pengarang",
        "Penerbit",
        "Tahun Terbit",
        "Kategori"
    };

    model = new DefaultTableModel(judul, 0);
    tblpeminjaman.setModel(model);
}
    
    private void nonAktif(){

    txtidanggota.setEditable(false);
    txtnamaanggota.setEditable(false);
    txtalamat.setEditable(false);

    txtidbuku.setEditable(false);
    txtjudul.setEditable(false);
    txtpengarang.setEditable(false);
    txtpenerbit.setEditable(false);
    txttahun.setEditable(false);
    txtkategori.setEditable(false);
}
    
    private void autoID() {
    try {
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(
            "SELECT id_peminjaman FROM peminjaman ORDER BY id_peminjaman DESC LIMIT 1"
        );

        if(rs.next()){

            String id = rs.getString("id_peminjaman").substring(2);

            int angka = Integer.parseInt(id) + 1;

            String nol = "";

            if(angka < 10){
                nol = "00";
            }else if(angka < 100){
                nol = "0";
            }

            txtidpinjam.setText("PJ"+nol+angka);

        }else{

            txtidpinjam.setText("PJ001");
        }

    } catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
}
    
private void resetForm() {
    autoID();

    sptanggal.setValue(new java.util.Date());
    sptenggat.setValue(new java.util.Date());

    txtidanggota.setText("");
    txtnamaanggota.setText("");
    txtalamat.setText("");

    txtidbuku.setText("");
    txtjudul.setText("");
    txtpengarang.setText("");
    txtpenerbit.setText("");
    txttahun.setText("");
    txtkategori.setText("");
}

public void cetakpeminjaman(String idPeminjaman) {
    try {
        String path = "./src/report/Peminjaman.jasper";

        HashMap parameter = new HashMap();
        parameter.put("id_peminjaman", idPeminjaman);
        parameter.put("nama_petugas", Session.getNamaPetugas());

        JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
        JasperViewer.viewReport(print, false);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Gagal mencetak report: " + ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtidanggota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnamaanggota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCariAnggota = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtidbuku = new javax.swing.JTextField();
        btnCariBuku = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtpenerbit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtjudul = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtpengarang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txttahun = new javax.swing.JTextField();
        txtkategori = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpeminjaman = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        txtidpinjam = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        sptanggal = new javax.swing.JSpinner();
        sptenggat = new javax.swing.JSpinner();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 1700));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 78, 59));
        jLabel1.setText("DATA PEMINJAMAN BUKU");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(6, 78, 59));
        jLabel7.setText("Id petugas");

        labelnama.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        labelnama.setForeground(new java.awt.Color(6, 78, 59));
        labelnama.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 78, 59));
        jLabel3.setText("Id Peminjaman");
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(71, 23));
        jLabel3.setMinimumSize(new java.awt.Dimension(71, 23));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(6, 78, 59));
        jLabel5.setText("Data Pelanggan");

        jPanel2.setBackground(new java.awt.Color(252, 247, 228));
        jPanel2.setPreferredSize(new java.awt.Dimension(480, 495));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(6, 78, 59));
        jLabel6.setText("Id Anggota");

        txtidanggota.addActionListener(this::txtidanggotaActionPerformed);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(6, 78, 59));
        jLabel8.setText("Nama");

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(6, 78, 59));
        jLabel10.setText("Alamat");

        btnCariAnggota.setBackground(new java.awt.Color(6, 78, 59));
        btnCariAnggota.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btnCariAnggota.setForeground(new java.awt.Color(255, 255, 255));
        btnCariAnggota.setText("Cari");
        btnCariAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCariAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCariAnggotaMouseExited(evt);
            }
        });
        btnCariAnggota.addActionListener(this::btnCariAnggotaActionPerformed);

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtidanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnamaanggota)
                    .addComponent(jScrollPane1))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamaanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(252, 247, 228));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(6, 78, 59));
        jLabel11.setText("Id Buku");

        btnCariBuku.setBackground(new java.awt.Color(6, 78, 59));
        btnCariBuku.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btnCariBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnCariBuku.setText("Cari");
        btnCariBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCariBukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCariBukuMouseExited(evt);
            }
        });
        btnCariBuku.addActionListener(this::btnCariBukuActionPerformed);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(6, 78, 59));
        jLabel12.setText("Judul Buku");

        jLabel13.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(6, 78, 59));
        jLabel13.setText("Pengarang");

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(6, 78, 59));
        jLabel14.setText("Penerbit");

        txtpengarang.addActionListener(this::txtpengarangActionPerformed);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(6, 78, 59));
        jLabel15.setText("Tahun Terbit");

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(6, 78, 59));
        jLabel16.setText("Kategori");

        btntambah.setBackground(new java.awt.Color(6, 78, 59));
        btntambah.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("Tambah");
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntambahMouseExited(evt);
            }
        });
        btntambah.addActionListener(this::btntambahActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(6, 78, 59));
        jLabel9.setText("Data Buku");

        jPanel4.setBackground(new java.awt.Color(252, 247, 228));

        tblpeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_peminjaman", "tanggal_pinjam", "id_anggota", "id_buku", "id_petugas", "tenggat_kembali"
            }
        ));
        tblpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpeminjamanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpeminjaman);

        btnhapus.setBackground(new java.awt.Color(6, 78, 59));
        btnhapus.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhapusMouseExited(evt);
            }
        });
        btnhapus.addActionListener(this::btnhapusActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhapus)
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhapus)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(6, 78, 59));
        jLabel17.setText("Peminjaman");

        jLabel18.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(6, 78, 59));
        jLabel18.setText("Nama Petugas");

        jLabel19.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(6, 78, 59));
        jLabel19.setText("Tanggal Peminjaman");

        labelid.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        labelid.setForeground(new java.awt.Color(6, 78, 59));
        labelid.setText("jLabel2");

        jLabel20.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(6, 78, 59));
        jLabel20.setText("Tenggat Pengembalian");

        btnsimpan.setBackground(new java.awt.Color(6, 78, 59));
        btnsimpan.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsimpanMouseExited(evt);
            }
        });
        btnsimpan.addActionListener(this::btnsimpanActionPerformed);

        btnbatal.setBackground(new java.awt.Color(6, 78, 59));
        btnbatal.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setText("Batal");
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbatalMouseExited(evt);
            }
        });
        btnbatal.addActionListener(this::btnbatalActionPerformed);

        btnclose.setBackground(new java.awt.Color(6, 78, 59));
        btnclose.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("Close");
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        btnclose.addActionListener(this::btncloseActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(354, 354, 354)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtidpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sptanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(626, 626, 626)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(sptenggat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel17))
                                .addGap(128, 128, 128)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sptanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sptenggat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1152, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
         int baris = tblpeminjaman.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(null, "Pilih buku yang ingin dihapus");
        return;
    }

    model.removeRow(baris);

    for (int i = 0; i < model.getRowCount(); i++) {
        model.setValueAt(i + 1, i, 0);
    }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tblpeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpeminjamanMouseClicked

    }//GEN-LAST:event_tblpeminjamanMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        if (txtidbuku.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Pilih buku terlebih dahulu");
        return;
    }

    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 1).toString().equals(txtidbuku.getText())) {
            JOptionPane.showMessageDialog(null, "Buku sudah ditambahkan");
            return;
        }
    }

    Object[] data = {
        model.getRowCount() + 1,
        txtidbuku.getText(),
        txtjudul.getText(),
        txtpengarang.getText(),
        txtpenerbit.getText(),
        txttahun.getText(),
        txtkategori.getText()
    };

    model.addRow(data);

    txtidbuku.setText("");
    txtjudul.setText("");
    txtpengarang.setText("");
    txtpenerbit.setText("");
    txttahun.setText("");
    txtkategori.setText("");
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtpengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpengarangActionPerformed

    private void btnCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBukuActionPerformed
        FormPopupBuku p = new FormPopupBuku();
        p.setVisible(true);
    }//GEN-LAST:event_btnCariBukuActionPerformed

    private void btnCariAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariAnggotaActionPerformed
        // TODO add your handling code here:
        FormPopupAnggota p = new FormPopupAnggota();
        p.setVisible(true);
    }//GEN-LAST:event_btnCariAnggotaActionPerformed

    private void txtidanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidanggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidanggotaActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String idPeminjaman = txtidpinjam.getText();

    try {
        if (txtidanggota.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih anggota terlebih dahulu");
            return;
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Tambahkan buku terlebih dahulu");
            return;
        }

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");

        String tanggal = fm.format(sptanggal.getValue());
        String tenggat = fm.format(sptenggat.getValue());

        conn.setAutoCommit(false);

        String sqlPeminjaman =
            "INSERT INTO peminjaman " +
            "(id_peminjaman, tanggal_pinjam, id_anggota, id_petugas, tenggat_kembali) " +
            "VALUES (?,?,?,?,?)";

        PreparedStatement pst = conn.prepareStatement(sqlPeminjaman);
        pst.setString(1, idPeminjaman);
        pst.setString(2, tanggal);
        pst.setString(3, txtidanggota.getText());
        pst.setString(4, Session.getIdPetugas());
        pst.setString(5, tenggat);
        pst.executeUpdate();

        String sqlIsi =
            "INSERT INTO isi_peminjaman (id_peminjaman, id_buku) VALUES (?,?)";

        String sqlUpdateBuku =
            "UPDATE buku SET status_buku='Dipinjam' WHERE id_buku=?";

        for (int i = 0; i < model.getRowCount(); i++) {
            String idBuku = model.getValueAt(i, 1).toString();

            PreparedStatement pstIsi = conn.prepareStatement(sqlIsi);
            pstIsi.setString(1, idPeminjaman);
            pstIsi.setString(2, idBuku);
            pstIsi.executeUpdate();

            PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdateBuku);
            pstUpdate.setString(1, idBuku);
            pstUpdate.executeUpdate();
        }

        conn.commit();

        JOptionPane.showMessageDialog(null, "Data peminjaman berhasil disimpan");

        cetakpeminjaman(idPeminjaman);

        resetForm();
        tampilData();

    } catch (Exception e) {
        try {
            conn.rollback();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        JOptionPane.showMessageDialog(null, e.getMessage());

    } finally {
        try {
            conn.setAutoCommit(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnCariAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariAnggotaMouseEntered
        // TODO add your handling code here:
        btnCariAnggota.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnCariAnggotaMouseEntered

    private void btnCariBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariBukuMouseEntered
        // TODO add your handling code here:
        btnCariBuku.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnCariBukuMouseEntered

    private void btntambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseEntered
        // TODO add your handling code here:
        btntambah.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btntambahMouseEntered

    private void btnhapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseEntered
        // TODO add your handling code here:
        btnhapus.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnhapusMouseEntered

    private void btnsimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseEntered
        // TODO add your handling code here:
        btnsimpan.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnsimpanMouseEntered

    private void btnbatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseEntered
        // TODO add your handling code here:
        btnbatal.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnbatalMouseEntered

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        btnclose.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btncloseMouseEntered

    private void btnCariAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariAnggotaMouseExited
        // TODO add your handling code here:
        btnCariAnggota.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnCariAnggotaMouseExited

    private void btnCariBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariBukuMouseExited
        // TODO add your handling code here:
        btnCariBuku.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnCariBukuMouseExited

    private void btntambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseExited
        // TODO add your handling code here:
        btntambah.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btntambahMouseExited

    private void btnhapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseExited
        // TODO add your handling code here:
        btnhapus.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnhapusMouseExited

    private void btnsimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseExited
        // TODO add your handling code here:
        btnsimpan.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnsimpanMouseExited

    private void btnbatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseExited
        // TODO add your handling code here:
        btnbatal.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnbatalMouseExited

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        btnclose.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btncloseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPeminjaman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariAnggota;
    private javax.swing.JButton btnCariBuku;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labelnama;
    private javax.swing.JSpinner sptanggal;
    private javax.swing.JSpinner sptenggat;
    private javax.swing.JTable tblpeminjaman;
    public static javax.swing.JTextArea txtalamat;
    public static javax.swing.JTextField txtidanggota;
    public static javax.swing.JTextField txtidbuku;
    private javax.swing.JTextField txtidpinjam;
    public static javax.swing.JTextField txtjudul;
    public static javax.swing.JTextField txtkategori;
    public static javax.swing.JTextField txtnamaanggota;
    public static javax.swing.JTextField txtpenerbit;
    public static javax.swing.JTextField txtpengarang;
    public static javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables
}
