/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author xiels
 */
public class FormPopupPengembalian extends javax.swing.JFrame {
    Connection conn = koneksi.getKoneksi();
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPopupPengembalian.class.getName());

    /**
     * Creates new form FormPopupPengembalian
     */
    public FormPopupPengembalian() {
        initComponents();
        tampilData();
        setLocationRelativeTo(null);
    }
    
    private void tampilData() {

    model = new DefaultTableModel();

    model.addColumn("ID Pengembalian");
    model.addColumn("ID Peminjaman");
    model.addColumn("Tanggal Kembali");
    model.addColumn("Tenggat Kembali");
    model.addColumn("Hari Terlambat");
    model.addColumn("Jumlah Buku");
    model.addColumn("Total Denda");

    String cari = txtcari.getText();

    try {

        int dendaPerHari = 1000;

        Statement st = conn.createStatement();

        String sql = "SELECT "
                   + "pengembalian.id_pengembalian, "
                   + "pengembalian.id_peminjaman, "
                   + "DATE_FORMAT(pengembalian.tanggal_kembali, '%Y-%m-%d') AS tanggal_kembali, "
                   + "DATE_FORMAT(peminjaman.tenggat_kembali, '%Y-%m-%d') AS tenggat_kembali, "
                   + "DATEDIFF(pengembalian.tanggal_kembali, peminjaman.tenggat_kembali) AS hari_terlambat, "
                   + "COUNT(isi_peminjaman.id_buku) AS jumlah_buku, "
                   + "DATEDIFF(pengembalian.tanggal_kembali, peminjaman.tenggat_kembali) "
                   + "* COUNT(isi_peminjaman.id_buku) "
                   + "* " + dendaPerHari + " AS total_denda "
                   + "FROM pengembalian "
                   + "JOIN peminjaman ON pengembalian.id_peminjaman = peminjaman.id_peminjaman "
                   + "JOIN isi_peminjaman ON peminjaman.id_peminjaman = isi_peminjaman.id_peminjaman "
                   + "WHERE DATEDIFF(pengembalian.tanggal_kembali, peminjaman.tenggat_kembali) > 0 "
                   + "AND pengembalian.id_pengembalian NOT IN "
                   + "(SELECT id_pengembalian FROM denda) "
                   + "AND (pengembalian.id_pengembalian LIKE '%" + cari + "%' OR "
                   + "pengembalian.id_peminjaman LIKE '%" + cari + "%') "
                   + "GROUP BY "
                   + "pengembalian.id_pengembalian, "
                   + "pengembalian.id_peminjaman, "
                   + "pengembalian.tanggal_kembali, "
                   + "peminjaman.tenggat_kembali "
                   + "ORDER BY pengembalian.id_pengembalian ASC";

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_pengembalian"),
                rs.getString("id_peminjaman"),
                rs.getString("tanggal_kembali"),
                rs.getString("tenggat_kembali"),
                rs.getString("hari_terlambat"),
                rs.getString("jumlah_buku"),
                rs.getString("total_denda")
            });
        }

        jTable1.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcari = new javax.swing.JTextField();
        btncaripengembalian = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));

        btncaripengembalian.setBackground(new java.awt.Color(6, 78, 59));
        btncaripengembalian.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btncaripengembalian.setForeground(new java.awt.Color(255, 255, 255));
        btncaripengembalian.setText("Cari");
        btncaripengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncaripengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncaripengembalianMouseExited(evt);
            }
        });
        btncaripengembalian.addActionListener(this::btncaripengembalianActionPerformed);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 78, 59));
        jLabel2.setText("Pop Up Pengembalian");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pengembalian", "ID Peminjaman", "Tanggal Kembali", "Status Pengembalian"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncaripengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncaripengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncaripengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripengembalianActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btncaripengembalianActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();

        String idPengembalian = jTable1.getValueAt(baris, 0).toString();
        String tanggalKembali = jTable1.getValueAt(baris, 2).toString();
        String tenggatKembali = jTable1.getValueAt(baris, 3).toString();
        String hariTerlambat = jTable1.getValueAt(baris, 4).toString();
        String totalDenda = jTable1.getValueAt(baris, 6).toString();

        FormDenda.idpengembalian.setText(idPengembalian);
        FormDenda.txttglkembali.setText(tanggalKembali);
        FormDenda.txttgtkembali.setText(tenggatKembali);
        FormDenda.txthariterlambat.setText(hariTerlambat);

        FormDenda.hitungDendaOtomatis();

        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btncaripengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaripengembalianMouseExited
        // TODO add your handling code here:
        btncaripengembalian.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btncaripengembalianMouseExited

    private void btncaripengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaripengembalianMouseEntered
        // TODO add your handling code here:
        btncaripengembalian.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btncaripengembalianMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPopupPengembalian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncaripengembalian;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
