/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author xiels
 */
public class FormPopupAnggota extends javax.swing.JFrame {
    Connection conn = koneksi.getKoneksi();
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPopupAnggota.class.getName());

    /**
     * Creates new form FormPopupAnggota
     */
    public FormPopupAnggota() {
        initComponents();
        tampilAnggota();
        datatable();
        setLocationRelativeTo(null);
    }
    private void tampilAnggota() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");

        try {

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(
                "SELECT * FROM anggota"
            );

            while (rs.next()) {

                model.addRow(new Object[]{

                    rs.getString("id_anggota"),
                    rs.getString("nama_anggota"),
                    rs.getString("alamat")
                });
            }

            tblanggota.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    protected void datatable() {
    Object[] Baris = {"Id Anggota", "Nama", "No.Hp", "Jenis Kelamin", "Alamat"};
    DefaultTableModel tabmode = new DefaultTableModel(null, Baris);

    String cari = txtcari.getText();

    try {
        Connection conn = koneksi.getKoneksi();
        Statement stat = conn.createStatement();

        String sql = "SELECT * FROM anggota WHERE " +
                     "id_anggota LIKE '%" + cari + "%' OR " +
                     "nama_anggota LIKE '%" + cari + "%' OR " +
                     "jenis_kelamin LIKE '%" + cari + "%' OR " +
                     "no_hp LIKE '%" + cari + "%'";

        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("id_anggota"),
                hasil.getString("nama_anggota"),
                hasil.getString("jenis_kelamin"),
                hasil.getString("no_hp"),
                hasil.getString("alamat"),
            });
        }

        tblanggota.setModel(tabmode);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btnCariAnggota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblanggota = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 78, 59));
        jLabel1.setText("Pop Up Anggota");

        btnCariAnggota.setBackground(new java.awt.Color(6, 78, 59));
        btnCariAnggota.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btnCariAnggota.setForeground(new java.awt.Color(255, 255, 255));
        btnCariAnggota.setText("Cari");
        btnCariAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCariAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCariAnggotaMouseExited(evt);
            }
        });
        btnCariAnggota.addActionListener(this::btnCariAnggotaActionPerformed);

        tblanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Anggota", "Nama", "No.Hp", "Jenis Kelamin", "Alamat"
            }
        ));
        tblanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblanggotaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblanggota);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariAnggotaActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_btnCariAnggotaActionPerformed

    private void tblanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblanggotaMouseClicked
        // TODO add your handling code here:
        int baris = tblanggota.getSelectedRow();

        String id = tblanggota.getValueAt(baris, 0).toString();
        String nama = tblanggota.getValueAt(baris, 1).toString();
        String alamat = tblanggota.getValueAt(baris, 2).toString();

        FormPeminjaman.txtidanggota.setText(id);
        FormPeminjaman.txtnamaanggota.setText(nama);
        FormPeminjaman.txtalamat.setText(alamat);
    dispose();
    }//GEN-LAST:event_tblanggotaMouseClicked

    private void btnCariAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariAnggotaMouseEntered
        // TODO add your handling code here:
        btnCariAnggota.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnCariAnggotaMouseEntered

    private void btnCariAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariAnggotaMouseExited
        // TODO add your handling code here:
        btnCariAnggota.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnCariAnggotaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPopupAnggota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariAnggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblanggota;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
