/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.awt.Color;
/**
 *
 * @author xiels
 */
public class MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnanggota = new javax.swing.JButton();
        btnbuku = new javax.swing.JButton();
        btnpeminjaman = new javax.swing.JButton();
        btnpengembalian = new javax.swing.JButton();
        btndenda = new javax.swing.JButton();
        btnpetugas = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));

        btnanggota.setBackground(new java.awt.Color(6, 78, 59));
        btnanggota.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnanggota.setForeground(new java.awt.Color(255, 255, 255));
        btnanggota.setText("Data Anggota");
        btnanggota.setBorderPainted(false);
        btnanggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnanggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnanggotaMouseExited(evt);
            }
        });
        btnanggota.addActionListener(this::btnanggotaActionPerformed);

        btnbuku.setBackground(new java.awt.Color(6, 78, 59));
        btnbuku.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnbuku.setForeground(new java.awt.Color(255, 255, 255));
        btnbuku.setText("Data Buku");
        btnbuku.setBorderPainted(false);
        btnbuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbukuMouseExited(evt);
            }
        });
        btnbuku.addActionListener(this::btnbukuActionPerformed);

        btnpeminjaman.setBackground(new java.awt.Color(6, 78, 59));
        btnpeminjaman.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnpeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        btnpeminjaman.setText("Peminjaman");
        btnpeminjaman.setBorderPainted(false);
        btnpeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpeminjamanMouseExited(evt);
            }
        });
        btnpeminjaman.addActionListener(this::btnpeminjamanActionPerformed);

        btnpengembalian.setBackground(new java.awt.Color(6, 78, 59));
        btnpengembalian.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnpengembalian.setForeground(new java.awt.Color(255, 255, 255));
        btnpengembalian.setText("Pengembalian");
        btnpengembalian.setBorderPainted(false);
        btnpengembalian.setFocusPainted(false);
        btnpengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpengembalianMouseExited(evt);
            }
        });
        btnpengembalian.addActionListener(this::btnpengembalianActionPerformed);

        btndenda.setBackground(new java.awt.Color(6, 78, 59));
        btndenda.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btndenda.setForeground(new java.awt.Color(255, 255, 255));
        btndenda.setText("Denda");
        btndenda.setBorderPainted(false);
        btndenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndendaMouseExited(evt);
            }
        });
        btndenda.addActionListener(this::btndendaActionPerformed);

        btnpetugas.setBackground(new java.awt.Color(6, 78, 59));
        btnpetugas.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnpetugas.setForeground(new java.awt.Color(255, 255, 255));
        btnpetugas.setText("Data Petugas");
        btnpetugas.setBorderPainted(false);
        btnpetugas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpetugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpetugasMouseExited(evt);
            }
        });
        btnpetugas.addActionListener(this::btnpetugasActionPerformed);

        btnlogout.setBackground(new java.awt.Color(6, 78, 59));
        btnlogout.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Logout");
        btnlogout.setBorderPainted(false);
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });
        btnlogout.addActionListener(this::btnlogoutActionPerformed);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 78, 59));
        jLabel1.setText("Menu Utama");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 78, 59));
        jLabel2.setText("Dashboard");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/55726824-4f3e-55b9-be3c-839322a244a8_150max.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(6, 78, 59));
        jLabel8.setText("Perpustakaan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnanggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpengembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpeminjaman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 78, 59));
        jLabel3.setText("SISTEM INFORMASI PERPUSTAKAAN");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 78, 59));
        jLabel4.setText("Selamat Datang di Halaman Utama");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/ornamen_kecil_100.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/buku_bunga_260.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/ranting_bunga_horizontal_220.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/ranting_bunga_gantung_180.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/bunga_sakura_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(180, 180, 180))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel7)))
                .addGap(527, 527, 527))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanggotaActionPerformed
        // TODO add your handling code here:
        new FormAnggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnanggotaActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpetugasActionPerformed
        // TODO add your handling code here:
        new FormPetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpetugasActionPerformed

    private void btnanggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanggotaMouseEntered
        // TODO add your handling code here:
        btnanggota.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnanggotaMouseEntered

    private void btnanggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanggotaMouseExited
        // TODO add your handling code here:\
        btnanggota.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnanggotaMouseExited

    private void btnbukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbukuMouseEntered
        // TODO add your handling code here:
        btnbuku.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnbukuMouseEntered

    private void btnpetugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpetugasMouseEntered
        // TODO add your handling code here:
        btnpetugas.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnpetugasMouseEntered

    private void btnpeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpeminjamanMouseEntered
        // TODO add your handling code here:
        btnpeminjaman.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnpeminjamanMouseEntered

    private void btnpengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpengembalianMouseEntered
        // TODO add your handling code here:
        btnpengembalian.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnpengembalianMouseEntered

    private void btndendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndendaMouseEntered
        // TODO add your handling code here:
        btndenda.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btndendaMouseEntered

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        btnlogout.setBackground(new java.awt.Color(25,135,84));
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnbukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbukuMouseExited
        // TODO add your handling code here:
        btnbuku.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnbukuMouseExited

    private void btnpetugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpetugasMouseExited
        // TODO add your handling code here:
        btnpetugas.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnpetugasMouseExited

    private void btnpeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpeminjamanMouseExited
        // TODO add your handling code here:
        btnpeminjaman.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnpeminjamanMouseExited

    private void btnpengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpengembalianMouseExited
        // TODO add your handling code here:
        btnpengembalian.setBackground(new java.awt.Color(6,78,59)); 
    }//GEN-LAST:event_btnpengembalianMouseExited

    private void btndendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndendaMouseExited
        // TODO add your handling code here:
        btndenda.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btndendaMouseExited

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        btnlogout.setBackground(new java.awt.Color(6,78,59));
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbukuActionPerformed
        // TODO add your handling code here:
        new FormBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbukuActionPerformed

    private void btnpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpeminjamanActionPerformed
        // TODO add your handling code here:
        new FormPeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpeminjamanActionPerformed

    private void btnpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpengembalianActionPerformed
        // TODO add your handling code here:
        new FormPengembalian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpengembalianActionPerformed

    private void btndendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndendaActionPerformed
        // TODO add your handling code here:
        new FormDenda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanggota;
    private javax.swing.JButton btnbuku;
    private javax.swing.JButton btndenda;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpeminjaman;
    private javax.swing.JButton btnpengembalian;
    private javax.swing.JButton btnpetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
